# This Pipeline deploys the SAP landing zone with Terraform

parameters:
- name: location
  displayName: Target Region
  type: string
  default: "West Europe"
  values:
  - "West Europe"
  - "France Central"
  - "Germany West Central"

trigger:
  none

pool:
  vmImage: ubuntu-latest
#  name: $(AgentPool)

name: SAP-Landingzone-Deployment_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

steps:
- script: |
    #!/bin/bash
    mkdir -p ~/bin
    wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
    unzip terraform_0.15.5_linux_amd64.zip
    mv terraform ~/bin
    export PATH=$PATH:~/bin
    mkdir ~/Azure_SAP_Automated_Deployment; cd $_
    git clone --single-branch --branch beta https://github.com/Azure/sap-hana.git
    git clone https://github.com/mimergel/sap-hana.config.git
  displayName: Run Prepare Script
  failOnStderr: false

- script: |
    #!/bin/bash
    mkdir -p ~/Inventory
    echo $(arm_output) > ~/Inventory/testfile.json
  displayName: Write Inventory JSON
  failOnStderr: false