# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:

- name: sap_sid
  displayName: SAP SID
  type: string
  default: X00

- name: baseosconfig
  displayName: Base OS Config
  type: boolean
  default: true

- name: saposconfig
  displayName: SAP specific OS Config
  type: boolean
  default: false

- name: bomprocessing
  displayName: BOM Processing
  type: boolean
  default: false

- name: hanadbinstall
  displayName: HANA DB Install 
  type: boolean
  default: false

- name: scsinstall
  displayName: SCS Install
  type: boolean
  default: false

- name: dbload
  displayName: DB Load
  type: boolean
  default: false

- name: pasinstall
  displayName: PAS Install
  type: boolean
  default: false

- name: appinstall
  displayName: APP Install
  type: boolean
  default: false

- name: webdispinstall
  displayName: WebDisp Install
  type: boolean
  default: false

- name: hsrsetup
  displayName: HSR Setup
  type: boolean
  default: false

- name: pacemakersetup
  displayName: Pacemaker Setup
  type: boolean
  default: false

- name: pacemakerscssetup
  displayName: Pacemaker SCS Setup
  type: boolean
  default: false

- name: pacemakerhanasetup
  displayName: Pacemaker HANA Setup
  type: boolean
  default: false

trigger:
  none

pool:
  name: $(agent)

# variables:

stages:
- stage: Publish_Pipeline_Artifact
  jobs:
  - job: Publish_Pipeline_Artifact
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: hana

- stage: BaseOSConfig
  condition: eq(${{ parameters.baseosconfig }}, true)
  jobs:
  - job: BaseOSConfig
    steps:
    - checkout: none
    - task: Ansible@0
      displayName: BaseOSConfig
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: '${DEPLOYMENT_REPO_PATH}/deploy/ansible/playbook_01_os_base_config.yaml'
        inventoriesAgentMachine: inlineContent
        inventoryInlineContentAgentMachine: |
          [hana]
          10.110.0.4
        args: -vv 