# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:

- name: osprep
  displayName: OS Preparations
  type: boolean
  default: true

trigger:
  none

pool:
  name: $(agent)

# variables:

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Ansible@0
  displayName: Base OS Config
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: 'file path playbook'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: 'ansible.cfg'

    - task: Ansible@0
      displayName: 'OS Preparations RHEL7 / SLES 12 (Ansible)'
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: 'playbook_01_os_base_config.yaml'
        inventoriesAgentMachine: inlineContent
        inventoryInlineContentAgentMachine: |
          [hana]
          $(privateip)
        args: -vv 