# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:

- name: baseosconfig
  displayName: Base OS Config
  type: boolean
  default: true

- name: saposconfig
  displayName: SAP specific OS Config
  type: boolean
  default: true

- name: bomprocessing
  displayName: BOM Processing
  type: boolean
  default: true

- name: hanadbinstall
  displayName: HANA DB Install 
  type: boolean
  default: true

- name: scsinstall
  displayName: SCS Install
  type: boolean
  default: true

- name: saposconfig
  displayName: DB Load
  type: boolean
  default: true

- name: pasinstall
  displayName: PAS Install
  type: boolean
  default: true

- name: appinstall
  displayName: APP Install
  type: boolean
  default: false

- name: webdispinstall
  displayName: WebDisp Install
  type: boolean
  default: false

- name: hsrsetup
  displayName: HSR Setup
  type: boolean
  default: false

- name: pacemakersetup
  displayName: Pacemaker Setup
  type: boolean
  default: false

- name: pacemakerscssetup
  displayName: Pacemaker SCS Setup
  type: boolean
  default: false

- name: pacemakerhanasetup
  displayName: Pacemaker HANA Setup
  type: boolean
  default: false


trigger:
  none

pool:
  name: $(agent)

# variables:

stages:
- stage: Publish_Pipeline_Artifact
  jobs:
  - job: Publish_Pipeline_Artifact
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: hana

- stage: Base-OS-Config
  condition: eq(${{ osprep }}, true)
  jobs:
  - job: Base-OS-Config
    steps:
    - checkout: none
    - task: Ansible@0
      displayName: 'Base OS Config'
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: 'playbook_01_os_base_config.yaml'
        inventoriesAgentMachine: inlineContent
        inventoryInlineContentAgentMachine: |
          [hana]
          $(privateip)
        args: -vv 


- task: Ansible@0
  displayName: Base OS Config
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: 'file path playbook'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: 'ansible.cfg'

